"""empty message

Revision ID: e2234db75bef
Revises: 60700e9b2400
Create Date: 2022-10-19 20:10:32.222695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2234db75bef'
down_revision = '60700e9b2400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorito', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('favorito_ibfk_3', 'favorito', type_='foreignkey')
    op.create_foreign_key(None, 'favorito', 'user', ['user_id'], ['id'])
    op.drop_column('favorito', 'users_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorito', sa.Column('users_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorito', type_='foreignkey')
    op.create_foreign_key('favorito_ibfk_3', 'favorito', 'user', ['users_id'], ['id'])
    op.drop_column('favorito', 'user_id')
    # ### end Alembic commands ###
